/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.1 		*/
/*  Created On : 14-sept.-2023 7:52:45 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

-- Drop Sequences for Autonumber Columns
DROP SEQUENCE IF EXISTS public.car_brand_id_seq;
DROP SEQUENCE IF EXISTS public.car_model_id_seq;
DROP SEQUENCE IF EXISTS public.service_id_seq;
DROP SEQUENCE IF EXISTS public.spare_model_id_seq;
DROP SEQUENCE IF EXISTS public.spare_service_id_seq;

-- Drop Tables
DROP TABLE IF EXISTS public.car_brand CASCADE;
DROP TABLE IF EXISTS public.car_model CASCADE;
DROP TABLE IF EXISTS public.service CASCADE;
DROP TABLE IF EXISTS public.service_car_model CASCADE;
DROP TABLE IF EXISTS public.spare_model CASCADE;
DROP TABLE IF EXISTS public.spare_service CASCADE;

-- Create Tables
CREATE TABLE public.car_brand
(
    id serial PRIMARY KEY,
    name varchar(250) NULL,
    is_active boolean NULL
);

CREATE TABLE public.car_model
(
    id serial PRIMARY KEY,
    name varchar(250) NULL,
    is_active boolean NULL,
    car_brand_id bigint NULL,
    FOREIGN KEY (car_brand_id) REFERENCES public.car_brand (id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE public.service
(
    id serial PRIMARY KEY,
    name varchar(250) NULL,
    is_active boolean NULL,
    spare_service_id bigint NULL
);

CREATE TABLE public.service_car_model
(
    service_id bigint NULL,
    car_model_id bigint NULL,
    FOREIGN KEY (service_id) REFERENCES public.service (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (car_model_id) REFERENCES public.car_model (id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE public.spare_model
(
    id serial PRIMARY KEY,
    name varchar(250) NULL,
    is_active boolean NULL,
    spare_service_id bigint NULL,
    FOREIGN KEY (spare_service_id) REFERENCES public.spare_service(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE public.spare_service
(
    id serial PRIMARY KEY,
    name varchar(250) NULL,
    is_active boolean NULL,
    service_id bigint NULL,
    FOREIGN KEY (service_id) REFERENCES public.service (id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- Create Primary Keys, Indexes, Uniques, Checks
CREATE INDEX "IXFK_car_model_car_brand" ON public.car_model (car_brand_id ASC);
CREATE INDEX "IXFK_service_spare_service" ON public.service (spare_service_id ASC);
CREATE INDEX "IXFK_service_car_model_car_model" ON public.service_car_model (car_model_id ASC);
CREATE INDEX "IXFK_service_car_model_service" ON public.service_car_model (service_id ASC);
CREATE INDEX "IXFK_spare_model_car_model" ON public.spare_model (spare_service_id ASC);
CREATE INDEX "IXFK_spare_service_service" ON public.spare_service (service_id ASC);

-- Create Table Comments, Sequences for Autonumber Columns
CREATE SEQUENCE public.car_brand_id_seq START 1;
CREATE SEQUENCE public.car_model_id_seq START 1;
CREATE SEQUENCE public.service_id_seq START 1;
CREATE SEQUENCE public.spare_model_id_seq START 1;
CREATE SEQUENCE public.spare_service_id_seq START 1;
